from ximea import xiapi
import cv2
import time

cam = xiapi.Camera()
cam.open_device()
quit()



#settings
cam.set_exposure(20000)

#create instance of Image to store image data and metadata
img = xiapi.Image()

#start data acquisition
print('Starting data acquisition...')
cam.start_acquisition()

try:
    print('Starting video. Press CTRL+C to exit.')
    t0 = time.time()
    while True:
        cam.get_image(img)
        print img.acq_nframe, img.nframe

        
except KeyboardInterrupt:
    cv2.destroyAllWindows()

#stop data acquisition
print('Stopping acquisition...')
cam.stop_acquisition()

#stop communication
cam.close_device()

print('Done.')



xxx = ['AbsoluteOffsetX', 'AbsoluteOffsetY', 'DownsamplingX', 'DownsamplingY', 
'GPI_level', '__class__', '__ctypes_from_outparam__', 
'__delattr__', '__dict__', 
'__doc__', '__format__', '__getattribute__', 
'__hash__', '__init__', '__module__', '__new__', 
'__reduce__', '__reduce_ex__', '__repr__', 
'__setattr__', '__setstate__', '__sizeof__', 
'__str__', '__subclasshook__', '__weakref__', 
'_b_base_', '_b_needsfree_', '_fields_', 
'_objects', 
'acq_nframe', 'nframe', 
'black_level', 
'bp', 
'bp_size', 
'data_saturation', 
'exposure_sub_times_us[5]', 
'exposure_time_us', 
'flags', 'frm', 'gain_db', 
'get_bytes_per_pixel', 
'get_image_data_numpy', 
'get_image_data_raw', 
'height', 'width'
'image_user_data', 
'img_desc', 
'padding_x', 
'size', 
'transport_frm', 
'tsSec', 
'tsUSec', 
'wb_blue', 
'wb_green', 
'wb_red']


cam_fields = ['CAM_OPEN', '__class__', '__delattr__', 
'__dict__', '__doc__', '__format__', 
'__getattribute__', '__hash__', 
'__init__', '__module__', 
'__new__', 
'__reduce__', 
'__reduce_ex__', 
'__repr__', '__setattr__', '__sizeof__', '__str__', 
'__subclasshook__', '__weakref__', 

'close_device', 
'dev_id', 
'device', 
'disable_LUTEnable', 
'disable_aeag', 
'disable_apply_cms', 
'disable_auto_bandwidth_calculation', 
'disable_auto_wb', 
'disable_bpc', 
'disable_cam_enum_golden_enabled', 
'disable_cam_sensor_init_disabled', 
'disable_dbnc_en', 
'disable_ffc', 
'disable_hdr', 
'disable_horizontal_flip', 
'disable_lens_mode', 
'disable_new_process_chain_enable', 
'disable_output_bit_packing', 
'disable_recent_frame', 
'disable_reset_usb_if_bootloader', 
'disable_vertical_flip', 
'enable_LUTEnable', 
'enable_aeag', 
'enable_apply_cms', 
'enable_auto_bandwidth_calculation', 
'enable_auto_wb', 
'enable_bpc', 
'enable_cam_enum_golden_enabled', 
'enable_cam_sensor_init_disabled', 
'enable_dbnc_en', 
'enable_ffc', 
'enable_hdr', 
'enable_horizontal_flip', 
'enable_lens_mode', 
'enable_new_process_chain_enable', 
'enable_output_bit_packing', 
'enable_recent_frame', 
'enable_reset_usb_if_bootloader', 
'enable_vertical_flip', 

'get_LUTIndex', 
'get_LUTIndex_increment', 
'get_LUTIndex_maximum', 
'get_LUTIndex_minimum', 

'get_LUTValue', 
'get_LUTValue_increment', 
'get_LUTValue_maximum', 
'get_LUTValue_minimum', 

'get_acq_buffer_size', 
'get_acq_buffer_size_increment', 
'get_acq_buffer_size_maximum', 
'get_acq_buffer_size_minimum', 

'get_acq_buffer_size_unit', 
'get_acq_buffer_size_unit_increment', 
'get_acq_buffer_size_unit_maximum', 
'get_acq_buffer_size_unit_minimum', 

'get_acq_frame_burst_count', 
'get_acq_frame_burst_count_increment', 
'get_acq_frame_burst_count_maximum', 
'get_acq_frame_burst_count_minimum', 

'get_acq_timing_mode', 
'get_acq_timing_mode_increment', 
'get_acq_timing_mode_maximum', 
'get_acq_timing_mode_minimum', 

'get_acq_transport_buffer_commit', 
'get_acq_transport_buffer_commit_increment', 
'get_acq_transport_buffer_commit_maximum', 
'get_acq_transport_buffer_commit_minimum', 

'get_acq_transport_buffer_size', 
'get_acq_transport_buffer_size_increment', 
'get_acq_transport_buffer_size_maximum', 
'get_acq_transport_buffer_size_minimum', 

'get_acq_transport_packet_size', 
'get_acq_transport_packet_size_increment', 
'get_acq_transport_packet_size_maximum', 
'get_acq_transport_packet_size_minimum', 

'get_acquisition_status', 
'get_acquisition_status_increment', 
'get_acquisition_status_maximum', 
'get_acquisition_status_minimum', 

'get_acquisition_status_selector', 
'get_acquisition_status_selector_increment', 
'get_acquisition_status_selector_maximum', 
'get_acquisition_status_selector_minimum', 

'get_ae_max_limit', 
'get_ae_max_limit_increment', 
'get_ae_max_limit_maximum', 
'get_ae_max_limit_minimum', 

'get_aeag_level', 
'get_aeag_level_increment', 
'get_aeag_level_maximum', 
'get_aeag_level_minimum', 

'get_aeag_roi_height', 
'get_aeag_roi_height_increment', 
'get_aeag_roi_height_maximum', 
'get_aeag_roi_height_minimum', 

'get_aeag_roi_offset_x', 
'get_aeag_roi_offset_x_increment', 
'get_aeag_roi_offset_x_maximum', 
'get_aeag_roi_offset_x_minimum', 

'get_aeag_roi_offset_y', 
'get_aeag_roi_offset_y_increment', 
'get_aeag_roi_offset_y_maximum', 
'get_aeag_roi_offset_y_minimum', 

'get_aeag_roi_width', 
'get_aeag_roi_width_increment', 
'get_aeag_roi_width_maximum', 
'get_aeag_roi_width_minimum', 

'get_ag_max_limit', 
'get_ag_max_limit_increment', 
'get_ag_max_limit_maximum', 
'get_ag_max_limit_minimum', 

'get_api_progress_callback', 
'get_api_version', 

'get_available_bandwidth', 
'get_available_bandwidth_increment', 
'get_available_bandwidth_maximum', 
'get_available_bandwidth_minimum', 

'get_binning_horizontal', 
'get_binning_horizontal_increment', 
'get_binning_horizontal_maximum', 
'get_binning_horizontal_minimum', 

'get_binning_horizontal_mode', 
'get_binning_horizontal_mode_increment', 
'get_binning_horizontal_mode_maximum', 
'get_binning_horizontal_mode_minimum', 

'get_binning_horizontal_pattern', 
'get_binning_horizontal_pattern_increment', 
'get_binning_horizontal_pattern_maximum', 
'get_binning_horizontal_pattern_minimum', 

'get_binning_selector', 
'get_binning_selector_increment', 
'get_binning_selector_maximum', 
'get_binning_selector_minimum', 

'get_binning_vertical', 
'get_binning_vertical_increment', 
'get_binning_vertical_maximum', 
'get_binning_vertical_minimum', 

'get_binning_vertical_mode', 
'get_binning_vertical_mode_increment', 
'get_binning_vertical_mode_maximum', 
'get_binning_vertical_mode_minimum', 

'get_binning_vertical_pattern', 
'get_binning_vertical_pattern_increment', 
'get_binning_vertical_pattern_maximum', 
'get_binning_vertical_pattern_minimum', 

'get_bpc_list_selector', 
'get_bpc_list_selector_increment', 
'get_bpc_list_selector_maximum', 
'get_bpc_list_selector_minimum', 

'get_buffer_policy', 
'get_buffer_policy_increment', 
'get_buffer_policy_maximum', 
'get_buffer_policy_minimum', 

'get_buffers_queue_size', 
'get_buffers_queue_size_increment', 
'get_buffers_queue_size_maximum', 
'get_buffers_queue_size_minimum', 

'get_cam_simulators_count', 
'get_cam_simulators_count_increment', 
'get_cam_simulators_count_maximum', 
'get_cam_simulators_count_minimum', 

'get_ccMTX00', 
'get_ccMTX00_increment', 
'get_ccMTX00_maximum', 
'get_ccMTX00_minimum', 

'get_ccMTX01', 
'get_ccMTX01_increment', 
'get_ccMTX01_maximum', 
'get_ccMTX01_minimum', 

'get_ccMTX02', 
'get_ccMTX02_increment', 
'get_ccMTX02_maximum', 
'get_ccMTX02_minimum', 

'get_ccMTX03', 
'get_ccMTX03_increment', 
'get_ccMTX03_maximum', 
'get_ccMTX03_minimum', 

'get_ccMTX10', 
'get_ccMTX10_increment', 
'get_ccMTX10_maximum', 
'get_ccMTX10_minimum', 

'get_ccMTX11', 
'get_ccMTX11_increment', 
'get_ccMTX11_maximum', 
'get_ccMTX11_minimum', 

'get_ccMTX12', 
'get_ccMTX12_increment', 
'get_ccMTX12_maximum', 
'get_ccMTX12_minimum', 

'get_ccMTX13', 
'get_ccMTX13_increment', 
'get_ccMTX13_maximum', 
'get_ccMTX13_minimum', 

'get_ccMTX20', 
'get_ccMTX20_increment', 
'get_ccMTX20_maximum', 
'get_ccMTX20_minimum', 

'get_ccMTX21', 
'get_ccMTX21_increment', 
'get_ccMTX21_maximum', 
'get_ccMTX21_minimum', 

'get_ccMTX22', 
'get_ccMTX22_increment', 
'get_ccMTX22_maximum', 
'get_ccMTX22_minimum', 

'get_ccMTX23', 
'get_ccMTX23_increment', 
'get_ccMTX23_maximum', 
'get_ccMTX23_minimum', 

'get_ccMTX30', 
'get_ccMTX30_increment', 
'get_ccMTX30_maximum', 
'get_ccMTX30_minimum', 

'get_ccMTX31', 
'get_ccMTX31_increment', 
'get_ccMTX31_maximum', 
'get_ccMTX31_minimum', 

'get_ccMTX32', 
'get_ccMTX32_increment', 
'get_ccMTX32_maximum', 
'get_ccMTX32_minimum', 

'get_ccMTX33', 
'get_ccMTX33_increment', 
'get_ccMTX33_maximum', 
'get_ccMTX33_minimum', 

'get_cfa', 
'get_cfa_increment', 
'get_cfa_maximum', 
'get_cfa_minimum', 

'get_chip_temp', 
'get_chip_temp_increment', 
'get_chip_temp_maximum', 
'get_chip_temp_minimum', 

'get_cms', 
'get_cms_increment',
'get_cms_maximum', 
'get_cms_minimum', 
 
'get_cms_intent', 
'get_cms_intent_increment', 
'get_cms_intent_maximum', 
'get_cms_intent_minimum', 

'get_column_fpn_correction', 
'get_column_fpn_correction_increment', 
'get_column_fpn_correction_maximum', 
'get_column_fpn_correction_minimum', 

'get_cooling', 
'get_cooling_increment', 
'get_cooling_maximum', 
'get_cooling_minimum', 

'get_counter_selector', 
'get_counter_selector_increment', 
'get_counter_selector_maximum', 
'get_counter_selector_minimum', 

'get_counter_value', 
'get_counter_value_increment', 
'get_counter_value_maximum', 
'get_counter_value_minimum', 

'get_dbnc_pol', 
'get_dbnc_pol_increment', 
'get_dbnc_pol_maximum', 
'get_dbnc_pol_minimum', 

'get_dbnc_t0', 
'get_dbnc_t0_increment', 
'get_dbnc_t0_maximum', 
'get_dbnc_t0_minimum', 

'get_dbnc_t1', 
'get_dbnc_t1_increment', 
'get_dbnc_t1_maximum', 
'get_dbnc_t1_minimum', 

'get_debug_level', 
'get_debug_level_increment', 
'get_debug_level_maximum', 
'get_debug_level_minimum', 

'get_decimation_horizontal', 
'get_decimation_horizontal_increment', 
'get_decimation_horizontal_maximum', 
'get_decimation_horizontal_minimum', 

'get_decimation_horizontal_pattern', 
'get_decimation_horizontal_pattern_increment', 
'get_decimation_horizontal_pattern_maximum', 
'get_decimation_horizontal_pattern_minimum', 

'get_decimation_selector', 
'get_decimation_selector_increment', 
'get_decimation_selector_maximum', 
'get_decimation_selector_minimum', 

'get_decimation_vertical', 
'get_decimation_vertical_increment', 
'get_decimation_vertical_maximum', 
'get_decimation_vertical_minimum', 

'get_decimation_vertical_pattern', 
'get_decimation_vertical_pattern_increment', 
'get_decimation_vertical_pattern_maximum', 
'get_decimation_vertical_pattern_minimum', 

'get_defccMTX', 
'get_defccMTX_increment', 
'get_defccMTX_maximum', 
'get_defccMTX_minimum', 

'get_device_id', 
'get_device_info_string', 
'get_device_inst_path', 
'get_device_loc_path', 
'get_device_manifest', 

'get_device_model_id', 
'get_device_model_id_increment', 
'get_device_model_id_maximum', 
'get_device_model_id_minimum', 

'get_device_name', 

'get_device_reset', 
'get_device_reset_increment', 
'get_device_reset_maximum', 
'get_device_reset_minimum', 

'get_device_sens_sn', 
'get_device_sn', 

'get_device_temperature_ctrl_mode', 
'get_device_temperature_ctrl_mode_increment', 
'get_device_temperature_ctrl_mode_maximum', 
'get_device_temperature_ctrl_mode_minimum', 

'get_device_temperature_element_sel', 
'get_device_temperature_element_sel_increment', 
'get_device_temperature_element_sel_maximum', 
'get_device_temperature_element_sel_minimum', 

'get_device_temperature_element_val', 
'get_device_temperature_element_val_increment', 
'get_device_temperature_element_val_maximum', 
'get_device_temperature_element_val_minimum', 

'get_device_type', 

'get_device_unit_register_selector', 
'get_device_unit_register_selector_increment', 
'get_device_unit_register_selector_maximum', 
'get_device_unit_register_selector_minimum', 

'get_device_unit_register_value', 
'get_device_unit_register_value_increment', 
'get_device_unit_register_value_maximum', 
'get_device_unit_register_value_minimum', 

'get_device_unit_selector', 
'get_device_unit_selector_increment', 
'get_device_unit_selector_maximum', 
'get_device_unit_selector_minimum', 

'get_device_user_id', 

'get_downsampling', 
'get_downsampling_increment', 
'get_downsampling_maximum', 
'get_downsampling_minimum', 

'get_downsampling_type', 
'get_downsampling_type_increment', 
'get_downsampling_type_maximum', 
'get_downsampling_type_minimum', 

'get_dp_param_selector', 
'get_dp_param_selector_increment', 
'get_dp_param_selector_maximum', 
'get_dp_param_selector_minimum', 

'get_dp_param_value', 
'get_dp_param_value_increment', 
'get_dp_param_value_maximum', 
'get_dp_param_value_minimum', 

'get_dp_proc_selector', 
'get_dp_proc_selector_increment', 
'get_dp_proc_selector_maximum', 
'get_dp_proc_selector_minimum', 

'get_dp_unit_selector', 
'get_dp_unit_selector_increment', 
'get_dp_unit_selector_maximum', 
'get_dp_unit_selector_minimum', 

'get_drv_version', 

'get_exp_priority', 
'get_exp_priority_increment', 
'get_exp_priority_maximum', 
'get_exp_priority_minimum', 

'get_exposure', 

'get_exposure_burst_count', 
'get_exposure_burst_count_increment', 
'get_exposure_burst_count_maximum', 
'get_exposure_burst_count_minimum', 

'get_exposure_increment', 
'get_exposure_maximum', 
'get_exposure_minimum', 

'get_ext_feature', 
'get_ext_feature_increment', 
'get_ext_feature_maximum', 
'get_ext_feature_minimum', 

'get_ext_feature_selector', 
'get_ext_feature_selector_increment', 
'get_ext_feature_selector_maximum', 
'get_ext_feature_selector_minimum', 

'get_ffc_dark_field_file_name', 
'get_ffc_flat_field_file_name', 

'get_ffs_access_key', 
'get_ffs_access_key_increment', 
'get_ffs_access_key_maximum', 
'get_ffs_access_key_minimum', 

'get_ffs_file_id', 
'get_ffs_file_id_increment', 
'get_ffs_file_id_maximum', 
'get_ffs_file_id_minimum', 

'get_ffs_file_name', 

'get_ffs_file_size', 
'get_ffs_file_size_increment', 
'get_ffs_file_size_maximum', 
'get_ffs_file_size_minimum', 

'get_framerate', 
'get_framerate_increment', 
'get_framerate_maximum', 
'get_framerate_minimum', 

'get_free_ffs_size', 
'get_free_ffs_size_increment', 
'get_free_ffs_size_maximum', 
'get_free_ffs_size_minimum', 

'get_gain', 
'get_gain_increment', 
'get_gain_maximum', 
'get_gain_minimum', 

'get_gain_selector', 
'get_gain_selector_increment', 
'get_gain_selector_maximum', 
'get_gain_selector_minimum', 

'get_gammaC', 
'get_gammaC_increment', 
'get_gammaC_maximum', 
'get_gammaC_minimum', 

'get_gammaY', 
'get_gammaY_increment', 
'get_gammaY_maximum', 
'get_gammaY_minimum', 

'get_gpi_level', 
'get_gpi_level_increment', 
'get_gpi_level_maximum', 
'get_gpi_level_minimum', 

'get_gpi_mode', 
'get_gpi_mode_increment', 
'get_gpi_mode_maximum', 
'get_gpi_mode_minimum', 

'get_gpi_selector', 
'get_gpi_selector_increment', 
'get_gpi_selector_maximum', 
'get_gpi_selector_minimum', 

'get_gpo_mode', 
'get_gpo_mode_increment', 
'get_gpo_mode_maximum', 
'get_gpo_mode_minimum', 

'get_gpo_selector', 
'get_gpo_selector_increment', 
'get_gpo_selector_maximum', 
'get_gpo_selector_minimum', 

'get_hdr_kneepoint1', 
'get_hdr_kneepoint1_increment', 
'get_hdr_kneepoint1_maximum', 
'get_hdr_kneepoint1_minimum', 

'get_hdr_kneepoint2', 
'get_hdr_kneepoint2_increment', 
'get_hdr_kneepoint2_maximum', 
'get_hdr_kneepoint2_minimum', 

'get_hdr_kneepoint_count', 
'get_hdr_kneepoint_count_increment', 
'get_hdr_kneepoint_count_maximum', 
'get_hdr_kneepoint_count_minimum', 

'get_hdr_t1', 
'get_hdr_t1_increment', 
'get_hdr_t1_maximum', 
'get_hdr_t1_minimum', 

'get_hdr_t2', 
'get_hdr_t2_increment', 
'get_hdr_t2_maximum', 
'get_hdr_t2_minimum', 

'get_height', 
'get_height_increment', 
'get_height_maximum', 
'get_height_minimum', 

'get_hous_back_side_temp', 
'get_hous_back_side_temp_increment', 
'get_hous_back_side_temp_maximum', 
'get_hous_back_side_temp_minimum', 

'get_hous_temp', 
'get_hous_temp_increment', 
'get_hous_temp_maximum', 
'get_hous_temp_minimum', 

'get_hw_revision', 
'get_image', 

'get_image_black_level', 
'get_image_black_level_increment', 
'get_image_black_level_maximum', 
'get_image_black_level_minimum', 

'get_image_correction_selector', 
'get_image_correction_selector_increment', 
'get_image_correction_selector_maximum', 
'get_image_correction_selector_minimum', 

'get_image_correction_value', 
'get_image_correction_value_increment', 
'get_image_correction_value_maximum', 
'get_image_correction_value_minimum', 

'get_image_data_bit_depth', 
'get_image_data_bit_depth_increment', 
'get_image_data_bit_depth_maximum', 
'get_image_data_bit_depth_minimum', 

'get_image_user_data', 
'get_image_user_data_increment', 
'get_image_user_data_maximum', 
'get_image_user_data_minimum', 

'get_imgdataformat', 
'get_imgdataformat_increment', 
'get_imgdataformat_maximum', 
'get_imgdataformat_minimum', 

'get_imgdataformatrgb32alpha', 
'get_imgdataformatrgb32alpha_increment', 
'get_imgdataformatrgb32alpha_maximum', 
'get_imgdataformatrgb32alpha_minimum', 

'get_imgpayloadsize', 
'get_imgpayloadsize_increment', 
'get_imgpayloadsize_maximum', 
'get_imgpayloadsize_minimum', 

'get_input_cms_profile', 

'get_led_mode', 
'get_led_mode_increment', 
'get_led_mode_maximum', 
'get_led_mode_minimum', 

'get_led_selector', 
'get_led_selector_increment', 
'get_led_selector_maximum', 
'get_led_selector_minimum', 

'get_lens_aperture_index', 
'get_lens_aperture_index_increment', 
'get_lens_aperture_index_maximum', 
'get_lens_aperture_index_minimum', 

'get_lens_aperture_value', 
'get_lens_aperture_value_increment', 
'get_lens_aperture_value_maximum', 
'get_lens_aperture_value_minimum', 

'get_lens_comm_data', 

'get_lens_feature', 
'get_lens_feature_increment', 
'get_lens_feature_maximum', 
'get_lens_feature_minimum', 

'get_lens_feature_selector', 
'get_lens_feature_selector_increment', 
'get_lens_feature_selector_maximum', 
'get_lens_feature_selector_minimum', 

'get_lens_focal_length', 
'get_lens_focal_length_increment', 
'get_lens_focal_length_maximum', 
'get_lens_focal_length_minimum', 

'get_lens_focus_distance', 
'get_lens_focus_distance_increment', 
'get_lens_focus_distance_maximum', 
'get_lens_focus_distance_minimum', 

'get_lens_focus_move', 
'get_lens_focus_move_increment', 
'get_lens_focus_move_maximum', 
'get_lens_focus_move_minimum', 

'get_lens_focus_movement_value', 
'get_lens_focus_movement_value_increment', 
'get_lens_focus_movement_value_maximum', 
'get_lens_focus_movement_value_minimum', 

'get_limit_bandwidth', 
'get_limit_bandwidth_increment', 
'get_limit_bandwidth_maximum', 
'get_limit_bandwidth_minimum', 

'get_limit_bandwidth_mode', 
'get_limit_bandwidth_mode_increment', 
'get_limit_bandwidth_mode_maximum', 
'get_limit_bandwidth_mode_minimum', 

'get_manual_wb', 
'get_manual_wb_increment', 
'get_manual_wb_maximum', 
'get_manual_wb_minimum', 

'get_number_devices', 

'get_offsetX', 
'get_offsetX_increment', 
'get_offsetX_maximum', 
'get_offsetX_minimum', 

'get_offsetY', 
'get_offsetY_increment', 
'get_offsetY_maximum', 
'get_offsetY_minimum', 

'get_output_bit_depth', 
'get_output_bit_depth_increment', 
'get_output_bit_depth_maximum', 
'get_output_bit_depth_minimum', 

'get_output_bit_packing_type', 
'get_output_bit_packing_type_increment', 
'get_output_bit_packing_type_maximum', 
'get_output_bit_packing_type_minimum', 

'get_output_cms_profile', 
'get_param', 
'get_proc_engine', 
'get_proc_engine_increment', 
'get_proc_engine_maximum', 
'get_proc_engine_minimum', 

'get_proc_num_threads', 
'get_proc_num_threads_increment', 
'get_proc_num_threads_maximum', 
'get_proc_num_threads_minimum', 

'get_read_file_ffs', 

'get_region_mode', 
'get_region_mode_increment', 
'get_region_mode_maximum', 
'get_region_mode_minimum', 

'get_region_selector', 
'get_region_selector_increment', 
'get_region_selector_maximum', 
'get_region_selector_minimum', 

'get_row_fpn_correction', 
'get_row_fpn_correction_increment', 
'get_row_fpn_correction_maximum', 
'get_row_fpn_correction_minimum', 

'get_sens_defects_corr_list_content', 

'get_sensor_bit_depth', 
'get_sensor_bit_depth_increment', 
'get_sensor_bit_depth_maximum', 
'get_sensor_bit_depth_minimum', 

'get_sensor_board_temp', 
'get_sensor_board_temp_increment', 
'get_sensor_board_temp_maximum', 
'get_sensor_board_temp_minimum', 

'get_sensor_clock_freq_hz', 
'get_sensor_clock_freq_hz_increment', 
'get_sensor_clock_freq_hz_maximum', 
'get_sensor_clock_freq_hz_minimum', 

'get_sensor_clock_freq_index', 
'get_sensor_clock_freq_index_increment', 
'get_sensor_clock_freq_index_maximum', 
'get_sensor_clock_freq_index_minimum', 

'get_sensor_feature_selector', 
'get_sensor_feature_selector_increment', 
'get_sensor_feature_selector_maximum', 
'get_sensor_feature_selector_minimum', 

'get_sensor_feature_value', 
'get_sensor_feature_value_increment', 
'get_sensor_feature_value_maximum', 
'get_sensor_feature_value_minimum', 

'get_sensor_line_period', 
'get_sensor_line_period_increment', 
'get_sensor_line_period_maximum', 
'get_sensor_line_period_minimum', 

'get_sensor_mode', 
'get_sensor_mode_increment', 
'get_sensor_mode_maximum', 
'get_sensor_mode_minimum', 

'get_sensor_model_id', 
'get_sensor_model_id_increment', 
'get_sensor_model_id_maximum',
'get_sensor_model_id_minimum', 

'get_sensor_output_channel_count', 
'get_sensor_output_channel_count_increment', 
'get_sensor_output_channel_count_maximum', 
'get_sensor_output_channel_count_minimum', 

'get_sensor_taps', 
'get_sensor_taps_increment', 
'get_sensor_taps_maximum', 
'get_sensor_taps_minimum', 

'get_sharpness', 
'get_sharpness_increment', 
'get_sharpness_maximum', 
'get_sharpness_minimum', 

'get_shutter_type', 
'get_shutter_type_increment', 
'get_shutter_type_maximum', 
'get_shutter_type_minimum', 

'get_target_temp', 
'get_target_temp_increment', 
'get_target_temp_maximum', 
'get_target_temp_minimum', 

'get_temp', 
'get_temp_increment', 
'get_temp_maximum', 
'get_temp_minimum', 
'get_temp_selector', 
'get_temp_selector_increment', 
'get_temp_selector_maximum', 
'get_temp_selector_minimum', 

'get_test_pattern', 

'get_test_pattern_generator_selector', 
'get_test_pattern_generator_selector_increment', 
'get_test_pattern_generator_selector_maximum', 
'get_test_pattern_generator_selector_minimum', 

'get_test_pattern_increment', 
'get_test_pattern_maximum', 
'get_test_pattern_minimum', 

'get_timestamp', 
'get_timestamp_increment', 
'get_timestamp_maximum', 
'get_timestamp_minimum', 

'get_transport_data_target', 
'get_transport_data_target_increment', 
'get_transport_data_target_maximum', 
'get_transport_data_target_minimum', 

'get_transport_pixel_format', 
'get_transport_pixel_format_increment', 
'get_transport_pixel_format_maximum', 
'get_transport_pixel_format_minimum', 

'get_trigger_delay', 
'get_trigger_delay_increment', 
'get_trigger_delay_maximum', 
'get_trigger_delay_minimum', 

'get_trigger_overlap', 
'get_trigger_overlap_increment', 
'get_trigger_overlap_maximum', 
'get_trigger_overlap_minimum', 

'get_trigger_selector', 
'get_trigger_selector_increment', 
'get_trigger_selector_maximum', 
'get_trigger_selector_minimum', 

'get_trigger_software', 
'get_trigger_software_increment', 
'get_trigger_software_maximum', 
'get_trigger_software_minimum', 

'get_trigger_source', 
'get_trigger_source_increment', 
'get_trigger_source_maximum', 
'get_trigger_source_minimum', 

'get_ts_rst_mode', 
'get_ts_rst_mode_increment', 
'get_ts_rst_mode_maximum', 
'get_ts_rst_mode_minimum', 

'get_ts_rst_source', 
'get_ts_rst_source_increment', 
'get_ts_rst_source_maximum', 
'get_ts_rst_source_minimum', 

'get_used_ffs_size', 
'get_used_ffs_size_increment', 
'get_used_ffs_size_maximum', 
'get_used_ffs_size_minimum', 

'get_version_fpga1', 
'get_version_mcu1', 
'get_version_mcu2', 
'get_version_mcu3', 
'get_version_xmlman', 

'get_wb_kb', 
'get_wb_kb_increment', 
'get_wb_kb_maximum', 
'get_wb_kb_minimum', 

'get_wb_kg', 
'get_wb_kg_increment', 
'get_wb_kg_maximum', 
'get_wb_kg_minimum', 

'get_wb_kr', 
'get_wb_kr_increment', 
'get_wb_kr_maximum', 
'get_wb_kr_minimum', 

'get_wb_roi_height', 
'get_wb_roi_height_increment', 
'get_wb_roi_height_maximum', 
'get_wb_roi_height_minimum', 

'get_wb_roi_offset_x', 
'get_wb_roi_offset_x_increment', 
'get_wb_roi_offset_x_maximum', 
'get_wb_roi_offset_x_minimum', 

'get_wb_roi_offset_y', 
'get_wb_roi_offset_y_increment', 
'get_wb_roi_offset_y_maximum', 
'get_wb_roi_offset_y_minimum', 

'get_wb_roi_width', 
'get_wb_roi_width_increment', 
'get_wb_roi_width_maximum', 
'get_wb_roi_width_minimum', 

'get_width', 
'get_width_increment', 
'get_width_maximum', 
'get_width_minimum', 

'get_write_file_ffs', 
'get_xiapi_context_list', 
'handle', 
'is_LUTEnable', 
'is_aeag', 
'is_apply_cms', 
'is_auto_bandwidth_calculation', 
'is_auto_wb', 
'is_bpc', 
'is_cam_enum_golden_enabled', 
'is_cam_sensor_init_disabled', 
'is_dbnc_en', 
'is_ffc', 
'is_hdr', 
'is_horizontal_flip', 
'is_iscolor', 
'is_iscooled', 
'is_isexist', 
'is_lens_mode', 
'is_new_process_chain_enable', 
'is_output_bit_packing', 
'is_recent_frame', 
'is_reset_usb_if_bootloader', 
'is_vertical_flip', 
'open_device', 
'open_device_by', 
'open_device_by_SN', 
'open_device_by_path', 
'set_LUTIndex', 
'set_LUTValue', 
'set_acq_buffer_size', 
'set_acq_buffer_size_unit', 
'set_acq_frame_burst_count', 
'set_acq_timing_mode', 
'set_acq_transport_buffer_commit', 
'set_acq_transport_buffer_size', 
'set_acq_transport_packet_size', 

'set_acquisition_status_selector', 
'set_ae_max_limit', 
'set_aeag_level', 
'set_aeag_roi_height', 
'set_aeag_roi_offset_x', 
'set_aeag_roi_offset_y', 
'set_aeag_roi_width', 
'set_ag_max_limit', 
'set_api_progress_callback', 

'set_binning_horizontal', 
'set_binning_horizontal_mode', 
'set_binning_horizontal_pattern', 
'set_binning_selector', 
'set_binning_vertical', 
'set_binning_vertical_mode', 
'set_binning_vertical_pattern', 
'set_bpc_list_selector', 
'set_buffer_policy', 
'set_buffers_queue_size', 
'set_cam_simulators_count', 
'set_ccMTX00', 
'set_ccMTX01', 
'set_ccMTX02', 
'set_ccMTX03', 
'set_ccMTX10', 
'set_ccMTX11', 
'set_ccMTX12', 
'set_ccMTX13', 
'set_ccMTX20', 
'set_ccMTX21', 
'set_ccMTX22', 
'set_ccMTX23', 
'set_ccMTX30', 
'set_ccMTX31', 
'set_ccMTX32', 
'set_ccMTX33', 
'set_cms', 
'set_cms_intent', 
'set_column_fpn_correction', 
'set_cooling', 
'set_counter_selector', 
'set_dbnc_pol', 
'set_dbnc_t0', 
'set_dbnc_t1', 
'set_debug_level', 
'set_decimation_horizontal', 
'set_decimation_horizontal_pattern', 
'set_decimation_selector', 
'set_decimation_vertical', 
'set_decimation_vertical_pattern', 
'set_defccMTX', 
'set_device_reset', 
'set_device_temperature_ctrl_mode', 
'set_device_temperature_element_sel', 
'set_device_temperature_element_val', 
'set_device_unit_register_selector', 
'set_device_unit_register_value', 
'set_device_unit_selector', 
'set_downsampling', 
'set_downsampling_type', 
'set_dp_param_selector', 
'set_dp_param_value', 
'set_dp_proc_selector', 
'set_dp_unit_selector', 
'set_exp_priority', 
'set_exposure', 
'set_exposure_burst_count', 
'set_exposure_direct', 
'set_ext_feature', 
'set_ext_feature_selector', 
'set_ffc_dark_field_file_name', 
'set_ffc_flat_field_file_name', 
'set_ffs_access_key', 
'set_ffs_file_name', 
'set_framerate', 
'set_gain', 
'set_gain_direct', 
'set_gain_selector', 
'set_gammaC', 
'set_gammaY', 
'set_gpi_mode', 
'set_gpi_selector', 
'set_gpo_mode', 
'set_gpo_selector', 
'set_hdr_kneepoint1', 
'set_hdr_kneepoint2', 
'set_hdr_kneepoint_count', 
'set_hdr_t1', 
'set_hdr_t2', 
'set_height', 
'set_image_black_level', 
'set_image_correction_selector', 
'set_image_correction_value', 
'set_image_data_bit_depth', 
'set_image_user_data', 
'set_imgdataformat', 
'set_imgdataformatrgb32alpha', 
'set_input_cms_profile', 
'set_led_mode', 
'set_led_selector', 
'set_lens_aperture_index', 
'set_lens_aperture_value', 
'set_lens_feature', 
'set_lens_feature_selector', 
'set_lens_focus_move', 
'set_lens_focus_movement_value', 
'set_limit_bandwidth', 
'set_limit_bandwidth_mode', 
'set_manual_wb', 
'set_offsetX', 
'set_offsetY', 
'set_output_bit_depth', 
'set_output_bit_packing_type', 
'set_output_cms_profile', 
'set_param', 
'set_proc_engine', 
'set_proc_num_threads', 
'set_region_mode', 
'set_region_selector', 
'set_row_fpn_correction', 
'set_sens_defects_corr_list_content', 
'set_sensor_bit_depth', 
'set_sensor_clock_freq_hz', 
'set_sensor_clock_freq_index', 
'set_sensor_feature_selector', 
'set_sensor_feature_value', 
'set_sensor_line_period', 
'set_sensor_mode', 
'set_sensor_output_channel_count', 
'set_sensor_taps', 
'set_sharpness', 
'set_shutter_type', 
'set_target_temp', 
'set_temp_selector', 
'set_test_pattern', 
'set_test_pattern_generator_selector', 
'set_transport_data_target', 
'set_transport_pixel_format', 
'set_trigger_delay', 
'set_trigger_overlap', 
'set_trigger_selector', 
'set_trigger_software', 
'set_trigger_source', 
'set_ts_rst_mode', 
'set_ts_rst_source', 
'set_wb_kb', 
'set_wb_kg', 
'set_wb_kr', 
'set_wb_roi_height', 
'set_wb_roi_offset_x',
'set_wb_roi_offset_y', 
'set_wb_roi_width', 
'set_width', 
'set_write_file_ffs', 
'set_xiapi_context_list', 
'start_acquisition', 
'stop_acquisition']



